### ISSUE TITLE
Automate custom domains

### ISSUE THREAD

**Issue by sthulb** [awslabs/aws-data-api#2]
Today, custom domains require manual intervention. CloudFormation allows you to automate this using `AWS:: CertificateManager::Certificate` and domain validation options.

The addition of two config options, Hosted Zone ID and domain name, you can automate it.

**Comment by IanMeyers** [comment]
Agreed. The information on custom domain has to be injected into both the `config.json` and `cors.json`, but could then be combined with CFN. However, we'd need to run an embedded template to create the certificate and R53 entries first, capture the output, and then inject these into the chalice config.
